name: thingy
services: 
  db:
    container_name: db 
    image: ghcr.io/5e-bits/5e-database:latest
    ports:
      - '27017:27017'
  cache:
    container_name: db-cache
    image: valkey/valkey:latest
    ports:
      - '6379:6379'
  api:
    container_name: 5e-api
    image: ghcr.io/5e-bits/5e-srd-api:latest
    environment:
      MONGODB_URI: mongodb://db/5e-database
      REDIS_URL: redis://cache:6379
    ports:
      -  '3000:3000'
    depends_on:
      - db
      - cache
 #  thingy-dev:
 #    build:
 #      context: . 
 #    ports:
 #      - '8080:5173'
 #      # - 9229:9229
 #    working_dir: /code
 #    volumes:
 #      - ./thingy-app:/code
 #    command: npm run dev
 #    depends_on: 
 #      - api
 #

