services:
  db:
    image: ghcr.io/5e-bits/5e-database:latest
    ports:
      - '27017:27017'

  cache:
    image: valkey/valkey:latest
    ports:
      - '6379:6379'

  api:
    image: ghcr.io/5e-bits/5e-srd-api:latest
    environment:
      MONGODB_URI: mongodb://db/5e-database
      REDIS_URL: redis://cache:6379
    ports:
      - '3000:3000'
    depends_on:
      - db
      - cache
